### ISSUE TITLE
Entering 4 digits for the post code is not sufficient for locations sharing the same post code

### ISSUE THREAD

**Issue by soapernet** [izacus/hass-swissweather#10]
### Problem
Entering 4 digits for the post code is not sufficient for locations sharing the same post code.
At the line 14 of _meteo.py_ file, the post code (_plz_) is filled by default with zero.

### Current state
MeteoSwiss use 6 digits to define localities.
In most cases, it's the zip code followed by 2 zeros, but when towns share the same zip code, meteo swiss changes this last two digits to make the difference.

I found the correct last two digits under _id_ in the _window.__mchwebLocalforecastLocation_ script loaded into the MeteoSwiss weather forecast web page after chosing the correct city.
Perhaps there is a directory of locations with the id/plz from MeteoSwiss, but I haven't found it.

### Exemple
The post code _4566_ is used for three locality:
- _Kriegstetten_ with meteoswiss id: _456600_
- _Halten_ with meteoswiss id: _456602_
- _Oekingen_ with meteoswiss id: _456603_
To have the forcast for the correct locality, you need to input the correct 6 digits.
In some cases, there is no locality with the two zeros added by default

### Proposal
Change:
`FORECAST_URL= "https://app-prod-ws.meteoswiss-app.ch/v1/plzDetail?plz={}00"`
To:
`FORECAST_URL= "https://app-prod-ws.meteoswiss-app.ch/v1/plzDetail?plz={:<06d}"`

With this, the zip code will be filled with zeros only when necessary, and for specific locality the 6 correct digits can be entered directly.

**Comment by pavime** [comment]
Hello,
I'm facing the same error, 3 different locations with the same post code, but different MeteoSwissID.
Thank you for your work

**Comment by izacus** [comment]
I've implemented the proposal, let me know if its functional.
