### ISSUE TITLE
Forecasts for Wind Speed (Gusts)

### ISSUE THREAD

**Issue by haus51** [izacus/hass-swissweather#11]
Thank you very much for the integration!

It would be great if the wind gusts (and maybe also wind speed) appeared in the daily forecasts.

Are you considering integrating these? Or can you show how we can add it to the code ourselves?

**Comment by izacus** [comment]
Wind gust speed has been added to the hourly forecast (the source doesn't send data for per-day forecast however, so wind data is missing there).
