### ISSUE TITLE
Forecast doesn't get updated

### ISSUE THREAD

**Issue by mravizza** [izacus/hass-swissweather#3]
Hi, I'm pretty new with HA. Your swiss weather is very nice. Thanks a lot for implementing it. 

I run currently HA on a raspberry PI ([fullpageos version](https://github.com/guysoft/FullPageOS)). The current weather in the "[weather forecast card](https://www.home-assistant.io/dashboards/weather-forecast/)" gets updated from time to time but not the forecast on hourly basis. Is that a problem of your code or a problem of the "[weather forecast card](https://www.home-assistant.io/dashboards/weather-forecast/)"? Thanks for your support. 

Update: it seems that I need support by you: https://community.home-assistant.io/t/daily-or-hourly-weather-forecast-doesnt-get-updated/718132

![image](https://github.com/izacus/hass-swissweather/assets/4323818/4dc73592-f695-4b3e-9504-391c88fc6616)

**Comment by izacus** [comment]
I'm afraid I can't help you without any logs - can you please enable debug logging for the integration and paste full logs showing the forecast updates?

**Comment by mravizza** [comment]
Log sent by email.

**Comment by izacus** [comment]
I'm afraid I can't help here, this seems to be a UI issue.
