### ISSUE TITLE
Add pressure at the altitude of the station.

### ISSUE THREAD

**Issue by tdse13** [izacus/hass-swissweather#4]
Could you please add the value "Luftdruck QNH". Thank you.

**Comment by izacus** [comment]
Note that "Air Pressure" sensor is the pressure at the altitude of the station. I've added QFF and QNH which are defined as sea level pressures according to https://data.geo.admin.ch/ch.meteoschweiz.messwerte-aktuell/info/VQHA80_en.txt source.

**Comment by tdse13** [comment]
Thank you very much for your quick enhancement!
